### ISSUE TITLE
Newest update no longer makes server pop up to vanilla players 

### ISSUE THREAD

**Issue by Zuki101** [MikeS-MS/MikesTweaks#14]
Update 1.8.3 

When hosting a server on the newest update, it now thinks you have the BiggerLobby mod on, when you don't and stuffs you in with all the other BiggerLobby servers.

**Comment by MikeS-MS** [comment]
BiggerLobby uses the LC_API mod which is what makes you see only modded lobbies as well as some tools for mods. I do not use LC_API and do not mark my mod as modded only, so LC_API is the one detecting if any mods are present and tagging you as modded only lobbies. 

I have made myself clear in the modding discord that I will not tag my mod as "everyone needs to have it to play together" myself, as that would make people in friend groups that do not want to get mods whatsoever, but are fine with their friends using some, unable to play together. 

If you wish for that behaviour to not happen, either disable LC_API (if no other mods which you've downloaded depend on it) or take the issue to the creator of LC_API. Like maybe implementing a config option that allows "cheats" as that's what my mod is classified as in their code.

I can easily remove that restriction, but without informing the developer it will just be a cycle of me spoofing and them reimplementing the forced modded lobby on their side,

**Comment by Zuki101** [comment]
Thanks for informing me. Didn't know much about the LC_API, turns out most of the mods I was using don't need it in the first place, now that I've looked at it.

I did try to find you on the Lethal Company Modding discord first, but couldn't find anything to do with you, so I'm not sure if there's multiple modding discord servers for lethal company. As the one I think is the main one is https://discord.gg/XeyYqRdRGC

Anyways thankkkk youuu

**Comment by MikeS-MS** [comment]
Yeah I'm not in the modding discord that's listed on the Thunderstore, I'm in the [Unofficial Lethal Company](https://discord.gg/nYcQFEpXfU) discord which is like the main discord for everything Lethal Company, which also runs the Lethal Company subreddit and has a modding section.
