### ISSUE TITLE
[BUG] Something is odd with GlobalTimeSpeedMultiplier

### ISSUE THREAD

**Issue by Werfire** [MikeS-MS/MikesTweaks#17]
**Where does the issue happen (client-side/host-side/both)?:**
Tried only as solo host

**Explain the issue(s) in detail:**
I want to only use this mod for tweaking moons' prices and I noticed that when changing time multiplier to "vanilla" 1, game actually still becomes noticeably slower. By trial and error I calculated that vanilla speed is achieved when setting multiplier to something like 1.35 and I am not sure if it doesn't break anything else (monsters spawns, etc.)

**Comment by MikeS-MS** [comment]
I will take a look at it, that is most likely my fault for assuming the value of yet another variable that has one value in code which gets set to a different value using the editor similar to #13

**Comment by MikeS-MS** [comment]
Yeah it turns out it's 1.4 actually, will be fixed in the next patch (1.9.2)
