### ISSUE TITLE
[TYPO] Walkie Slot has the same desc as Flashlight Slot

### ISSUE THREAD

**Issue by SlonzyJr** [MikeS-MS/MikesTweaks#21]
![image](https://github.com/MikeS-MS/MikesTweaks/assets/82125422/3af765d0-a731-4aa6-bbd0-050f3b464291)

**Comment by MikeS-MS** [comment]
Yes it is a typo, will be fixed with the next update.

**Comment by MikeS-MS** [comment]
This has been fixed as of v2.0.2
