### ISSUE TITLE
[BUG] Mod Error W/ LateGameUpgrades

### ISSUE THREAD

**Issue by Barghest-Procedural** [MikeS-MS/MikesTweaks#24]
**Mods:**
```
 - LateGameUpgrades - 2.8.5 (status: enabled/disabled)
 - MikesTweaks - 2.0.1 (status: enabled/disabled)
 - Dependencies - (018cbd9e-9609-241a-5021-44e2bb4020a1) Profile Code
```

**Configs:**
```
LateGameUpgrades:
 ChangedConfigOption1 = None Changed, I tried disabling all items from this mod, error persisted.

 MikesTweaks:
 ChangedConfigOption1 = Tool Item weight values all set to 0, and store prices lowered slightly, I saw no difference in errors upon changing these.
 ```

**Where does the issue happen (client-side/host-side/both)?:**

Both sides experience this issue

**Explain the issue(s) in detail:**
_(Summary)_
There seems to be a conflict that breaks the stamina usage changes in Miketweaks when loaded alongside of LateGameUpgrades. as well as some other things:
_(Full Desc.)_
With just LateGameUpgrades mod with Mikes Tweaks (With dependencies) Loaded I get a large error from the 'CharacterController' in the command console (Check log). Upon loading into a match all users do not have altered Stamina nor item weight, values. Everything resets to vanilla it seems. This issue did not pop up about a week ago.
Other things like the inventory slots and store prices still work when loaded, however I am unsure if the day cycle is different or not.

I have also noticed some intermittent freezing at least on my machine when these two mods are loaded. This is also new behavior compared to less than a week ago.

**Steps for reproducing the issue (optional if you've tested it and found out what causes it):**
Just add those two mods, always has this issue regardless of user from my experience.
[LogOutput.log](https://github.com/MikeS-MS/MikesTweaks/files/13800009/LogOutput.log)

**Comment by MikeS-MS** [comment]
I've checked the other mod, it seems to also be inserting code where I am so that's what brakes mine. Will try to fix, but this might not be doable as both of us insert code replacement for the stamina recharge.

**Comment by MikeS-MS** [comment]
Will apply a quick fix for now by disabling my code insertion for the stamina regen if that mod is active. This means that if you are playing with LateGameUpgrades enabled, my stamina recharge values and jump stamina drain won't matter. If you want to enable them, you will have to exit the game, disable LateGameUpgrades and turn the game back on.

**Comment by Barghest-Procedural** [comment]
That is both great and unfortunate, I prefer just using your stamina changes for my server's configs, but it can't be helped atm it seems. With that, at least the mods won't fight each other so much when together. Perhaps LateGameUpgrades can create a fix or workaround that can use either both codes, or prefer one or the other, like a toggleable patch

**Comment by MikeS-MS** [comment]
I will implement a proper fix for this later, just patched it for the time being as to not completely break when playing with the 2 mods together.
