### ISSUE TITLE
[BUG] Flashlight toggle creates 2 light beams, walkie toggle doesnt work

### ISSUE THREAD

**Issue by miguelgdx** [MikeS-MS/MikesTweaks#25]
The mod seems to now collide with some other mods (or the other way around).
But for the flashlight issue this is how to reproduce it:

Have a flashlight (any kind)
Press "F" while holding the flashlight
You will notice there are now actually two flash beams
If you left click or use "F" to deactivate the flashlight, it will deactive one of the light beams, but not all.
I recorded a video where you see it works fine toggling it on and off from another item, but if you do it over the flashlight (pressing F) it will trigger the issue.

Also "R" key for walkie does not work (I tested it later).
Also the /toggleVisor command will not work with FOV mod
Here is a collection of mods (code) where you can see it: 018cbce7-27bc-917c-5b71-1247a1182645

https://github.com/MikeS-MS/MikesTweaks/assets/1567609/3d908dd9-7fec-4861-bc8f-d0f5593ee5ba

**Comment by MikeS-MS** [comment]
Should be fixed as of 2.0.2 keep me updated.

**Comment by miguelgdx** [comment]
The reported issues are now gone. Thanks
