### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by dragon4595** [MikeS-MS/MikesTweaks#3]
not host. can not access Terminal

**Comment by MikeS-MS** [comment]
Could you please elaborate? You're not the host and cannot access the Terminal?

**Comment by ShadowyBerry** [comment]
This is most likely unchanged by the host in the config file:

## Set this to false if you don't want people who join your lobby to be able to use the terminal and to true if you want them to be able to.
## You probably want to set this to true if you're hosting a lobby with people you know and trust.
## Vanilla Default: True
# Setting type: Boolean
# Default value: false
AllowClientsToUseTerminal = true

**Comment by ShadowyBerry** [comment]
This is most likely unchanged by the host in the config file:

```
## Set this to false if you don't want people who join your lobby to be able to use the terminal and to true if you want them to be able to.
## You probably want to set this to true if you're hosting a lobby with people you know and trust.
## Vanilla Default: True
# Setting type: Boolean
# Default value: false
AllowClientsToUseTerminal = false
```

**Comment by MikeS-MS** [comment]
Closing due to no further information and inactivity, if the issue persists reopen another issue.
