### ISSUE TITLE
v1.8: Config error

### ISSUE THREAD

**Issue by Haano137** [MikeS-MS/MikesTweaks#8]
Changing the value of `UseVanillaMoonCosts` from `false` into `true` causes this error.

![image](https://github.com/MikeS-MS/MikesTweaks/assets/71540568/cd28f5e7-c2f4-4680-9631-72ca15786eb5)

**Comment by MikeS-MS** [comment]
Just released a patch (1.8.1), should fix that issue, keep me updated.

**Comment by Haano137** [comment]
> Just released a patch (1.8.1), should fix that issue, keep me updated.

Bug's no more 👍
